### ISSUE TITLE
Issue when restart from checkpoint file (conflict with initial condition in PKs )

### ISSUE THREAD

**Issue by zexuanxu** [amanzi/ats#66] opened 2020-09-16 00:19 UTC
It seems when ATS master restarts a simulation from a checkpoint file, it does not overwrite the initial conditions set in the kernals (for example, pressure in the flow PK). In other words, when "initial conditions" is existing in the PKs, the simulation uses it instead of the fields in the checkpoint file. I believe in the previous version (0.87) the initial conditions are omitted and the checkpoint file is used regardless of the initial condition. 

I looked into   https://github.com/amanzi/ats/blob/31eb9c864e4625b8a5b1c2a0706018d1497a0ada/src/executables/coordinator.cc#L146
and found that the coordinator (seems like a new file - I don't see it in the previous version), it reads from the checkpoint, then call InitializeFields() that may overwrite everything from the checkpoint file?

Not sure if this is related to the PK initializations issue that Ethan and Daniil are working for the integrated hydro reactive transport. 

Thanks
Zexuan

**Comment by ecoon** [comment] 2020-09-16 13:28
That's problematic.  I'll take a look.

That file has always been there, but in a different directory.

**Comment by ecoon** [comment] 2020-09-16 13:44
Hmm, it looks like there is some odd interactions going on here in coordinator, pk_physical_default, and Field_CompositeVector as to when and if initialization code gets called.  Need a regression test with restart too apparently.  I'll have to fix this this afternoon.

**Comment by ecoon** [comment] 2020-09-17 02:17
@zexuanxu  is this on master?  Can you check for me on the ecoon/pk_cleanup branch?  I believe I have already fixed this in going over the PKs, and I confirmed that for a Richards PK at least, the restart works as expected (on that branch).  That branch will get merged into master very soon (end of the week).

**Comment by zexuanxu** [comment] 2020-09-17 05:08
@ecoon Yes this is on master. And I just checked on your ecoon/pk_cleanup, and confirmed that this has been fixed in this, and restart works as expected -  it just not on master yet. Thanks!

**Comment by ecoon** [comment] 2020-11-12 05:34
fixed in #64

**Closed by ecoon** 2020-11-12 05:34 UTC
