### ISSUE TITLE
Feature Request: Excluding Specified Components from Transport 

### ISSUE THREAD

**Issue by saubhagya-gatech** [amanzi/ats#149] opened 2022-08-24 20:37 UTC
A way to tell ATS transport to ignore transport for certain specified components. This will benefit various applications, kinetic sorption modeling is one of them. We would want to use these components in reactions but ignore for transport.

**Comment by ecoon** [comment] 2023-05-09 21:26
duplicate of #93

**Closed by ecoon** 2023-05-09 21:26 UTC
Labels: reactive-transport-roundup
