### ISSUE TITLE
Why the installation of ATS failed?

### ISSUE THREAD

**Issue by TJUCoastlabRGQ** [amanzi/ats#194] opened 2023-07-03 06:36 UTC
Hi everybody! I'm trying to install ATS locally. I clone the Amanzi source with the following command:
`git clone -b amanzi-1.5-dev http://github.com/amanzi/amanzi $AMANZI_SRC_DIR`
Later I run the build_ATS_generic.sh with the following command:
`. ${AMANZI_SRC_DIR}/build_ATS_generic.sh`
During the installation process, the third party libraries were installed successfully. However, when it comes to the installation of the ATS project the following error occurred:
`In file included from /home/gqrcqjtu/Software/ATSDEBUG/repos/amanzi/src/physics/ats/src/executables/test/Main.cc:16:0:
/home/gqrcqjtu/Software/ATSDEBUG/repos/amanzi/src/physics/ats/src/executables/ats_registration_files.hh:23:10: fatal error: models_transport_reg.hh: No such file or directory'
The above error log indicates that the head file is missing. I went to the amanzi project and found this file as "amanzi/src/pks/transport/models_transport_reg.hh". So I just downloaded this file and put it in the directory "repos/amanzi/src/pks/transport". Later I installed it again, and lots of errors occurred again, and one is as follows:
'/home/gqrcqjtu/Software/ATSDEBUG/repos/amanzi/src/pks/transport/models_transport_reg.hh:44:55: error: ‘Amanzi::Utils::RegisteredFactory<Amanzi::Transport::MDM, Amanzi::Transport::MDM_Bear> Amanzi::Transport::MDM_Bear::reg_’ is not a static data member of ‘class Amanzi::Transport::MDM_Bear’
 Utils::RegisteredFactory<MDM, MDM_Bear> MDM_Bear::reg_("Bear");' 

Whats the problem?

**Comment by lipnikov** [comment] 2023-07-03 19:06
This problem is hard to reproduce. I tried master branches of Amanzi and ATS in the Release mode and it worked with and without the transport header installed.  Can you provide more details, branches, tags, ATS environmental variables?

**Comment by TJUCoastlabRGQ** [comment] 2023-07-04 02:33
Ok! Thanks for your reply. The following is the ATS environmental variables:
"export ATS_BASE=/home/gqrcqjtu/Software/ATSDEBUG
export ATS_BUILD_TYPE=Debug
export ATS_VERSION=master
export OPENMPI_DIR=/usr/"
These four variables are set according to the configuration of my local laptop. The others are kept as suggested by the installation guide as follows:
"export AMANZI_TPLS_BUILD_DIR=${ATS_BASE}/amanzi_tpls-build-${ATS_VERSION}-${ATS_BUILD_TYPE}
export AMANZI_TPLS_DIR=${ATS_BASE}/amanzi_tpls-install-${ATS_VERSION}-${ATS_BUILD_TYPE}
export AMANZI_SRC_DIR=${ATS_BASE}/repos/amanzi
export AMANZI_BUILD_DIR=${ATS_BASE}/amanzi-build-${ATS_VERSION}-${ATS_BUILD_TYPE}
export AMANZI_DIR=${ATS_BASE}/amanzi-install-${ATS_VERSION}-${ATS_BUILD_TYPE}
export ATS_SRC_DIR=${AMANZI_SRC_DIR}/src/physics/ats
export ATS_DIR=${AMANZI_DIR}
export PATH=${ATS_DIR}/bin:${PATH}
export PATH=${AMANZI_TPLS_DIR}/bin:${PATH}
export PYTHONPATH=${ATS_SRC_DIR}/tools/utils:${PYTHONPATH}
export PYTHONPATH=${AMANZI_TPLS_DIR}/SEACAS/lib:${PYTHONPATH}"

Tag of the downloaded source code is "amanzi-1.5-dev", and I downloaded this version with command "git clone -b amanzi-1.5-dev http://github.com/amanzi/amanzi $AMANZI_SRC_DIR".
Other important configurations:
OS: Ubuntu 18.04 LTS;
Python: 2.7.17;
Cmake: 3.26.4;
curl: 8.1.2;
git: 2.17.1;

**Comment by jd-moulton** [comment] 2023-07-05 01:41
A couple of things to consider.  The tag amanzi-1.5-dev marks the beginning of development on the next release on the master branch.  It's not a good tag to clone, you really want the HEAD of the master branch.  So just  ```git checkout master``` in your source directory.   Also, we don't support python 2.x anymore, you need to have a python 3.x installation available.   A simple way to do that is with Anaconda, many of use the python 3.x from there.

**Comment by ecoon** [comment] 2023-07-10 19:49
I'm going to close this for now as "not a bug".  If David and Konstantin's help hasn't been enough, please join and reach out on the ATS user's group mailing list at https://groups.google.com/g/ats-users and we'll get you squared away!

**Closed by ecoon** 2023-07-10 19:49 UTC
